# Generated by Django 4.2.11 on 2025-02-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
