# Generated by Django 4.2.11 on 2025-02-12 17:49

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todo_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='list',
            field=models.ForeignKey(default=api.models.List.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='api.list'),
        ),
    ]
