# Generated by Django 4.2.11 on 2025-02-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='DateModel',
        ),
        migrations.RenameField(
            model_name='datemodel',
            old_name='date',
            new_name='dateVar',
        ),
    ]
